# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: StrictLLM.StrictLLM
PackageVersion: 2.2.12
InstallerType: nullsoft
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ProductCode: b97f3dde-3d3e-5c96-90a9-e425af909f62
AppsAndFeaturesEntries:
  - DisplayName: StrictLLM Chat
    Publisher: StrictLLM
Installers:
  - Architecture: x64
    Scope: user
    InstallerUrl: https://github.com/StrictLLM-LLC/download/releases/download/v2.2.12/StrictLLM-2.2.12-windows-x64-StrictLLM.Chat.Setup.2.2.12.exe
    InstallerSha256: 3061103C3B8A9347142A7110E946DE899D366F434DE1B074988195F614B0C7CF
    InstallerSwitches:
      Custom: /currentuser
  - Architecture: x64
    Scope: machine
    InstallerUrl: https://github.com/StrictLLM-LLC/download/releases/download/v2.2.12/StrictLLM-2.2.12-windows-x64-StrictLLM.Chat.Setup.2.2.12.exe
    InstallerSha256: 3061103C3B8A9347142A7110E946DE899D366F434DE1B074988195F614B0C7CF
    InstallerSwitches:
      Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
